version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      k8s:
        patterns:
          - kube
          - k8s-openapi
      server:
        patterns:
          - tonic*
          - prost*
          - hyper*
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
