[package]
name = "suffiks-ingress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
prost = "0.11.9"
tokio = { version = "1.28.2", features = ["full"] }
tokio-stream = "0.1.14"
tonic = "0.9.2"

[[bin]]
	name = "suffiks-ingress"
	path = "src/server.rs"

[build-dependencies]
tonic-build = "0.9.2"

