[package]
name = "suffiks-ingress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
env_logger = "0.10.0"
hyper-rustls = "0.24.0"
k8s-openapi = { version = "0.18.0", features = ["v1_26", "schemars"] }
kube = { version = "0.82.2", default-features = false, features = ["derive", "rustls-tls", "client", "config", "kube-derive"] }
log = "0.4.18"
prost = "0.11.9"
schemars = "0.8.12"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
tokio = { version = "1.28.2", features = ["full"] }
tokio-stream = "0.1.14"
tonic = { version = "0.9.2", features = ["tls"] }

[[bin]]
name = "crd"
path = "src/crd.rs"

[build-dependencies]
tonic-build = "0.9.2"

